### ISSUE TITLE
Questions about "upload my solution"

### ISSUE THREAD

**Issue by zhanghx0905** [SebLeich/storage-manager-2.0#10]
Hi, I'm working on the 3d pin packaging algorithm and found the visual interface you provided, which is very nice.

I have studied your code and I think the "upload my solution" feature is not perfect at the moment. IGood and IGroup are linked by group id which can't be known from the interface. What's more, I don't know exactly what to include in the uploaded JSON file.

Can you provide more documentation? Would you consider developing this feature further in the future? Thanks.

**Comment by SebLeich** [comment]
Hey, I'm glad you like the solution! Sure, I'm always open for suggestions. So please pass me your ideas more detailed. Alternatively, we can schedule a google meeting to talk about your findings!

About your upload problem: you can download the exemplary solution and pass your algorithm's results in accordance to the provided format. Additionally, I'm working on the process builder feature to build custom data pipelines and to connect custom solutions using a http RESTful interface.
Maybe you should wait until that feature works as expected?
